package com.virality.dishly.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DishAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAllPropertiesEquals(Dish expected, Dish actual) {
        assertDishAutoGeneratedPropertiesEquals(expected, actual);
        assertDishAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAllUpdatablePropertiesEquals(Dish expected, Dish actual) {
        assertDishUpdatableFieldsEquals(expected, actual);
        assertDishUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishAutoGeneratedPropertiesEquals(Dish expected, Dish actual) {
        assertThat(expected)
            .as("Verify Dish auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishUpdatableFieldsEquals(Dish expected, Dish actual) {
        assertThat(expected)
            .as("Verify Dish relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getPreparationTime()).as("check preparationTime").isEqualTo(actual.getPreparationTime()))
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getComposition()).as("check composition").isEqualTo(actual.getComposition()))
            .satisfies(e -> assertThat(e.getWeight()).as("check weight").isEqualTo(actual.getWeight()))
            .satisfies(e -> assertThat(e.getDishStatus()).as("check dishStatus").isEqualTo(actual.getDishStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDishUpdatableRelationshipsEquals(Dish expected, Dish actual) {
        assertThat(expected)
            .as("Verify Dish relationships")
            .satisfies(e -> assertThat(e.getKitchen()).as("check kitchen").isEqualTo(actual.getKitchen()))
            .satisfies(e -> assertThat(e.getMenu()).as("check menu").isEqualTo(actual.getMenu()));
    }
}
