package com.virality.dishly.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrdersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdersAllPropertiesEquals(Orders expected, Orders actual) {
        assertOrdersAutoGeneratedPropertiesEquals(expected, actual);
        assertOrdersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdersAllUpdatablePropertiesEquals(Orders expected, Orders actual) {
        assertOrdersUpdatableFieldsEquals(expected, actual);
        assertOrdersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdersAutoGeneratedPropertiesEquals(Orders expected, Orders actual) {
        assertThat(expected)
            .as("Verify Orders auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdersUpdatableFieldsEquals(Orders expected, Orders actual) {
        assertThat(expected)
            .as("Verify Orders relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getUpdatedAt()).as("check updatedAt").isEqualTo(actual.getUpdatedAt()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getSum()).as("check sum").isEqualTo(actual.getSum()))
            .satisfies(e -> assertThat(e.getPaymentMethod()).as("check paymentMethod").isEqualTo(actual.getPaymentMethod()))
            .satisfies(e -> assertThat(e.getPaymentStatus()).as("check paymentStatus").isEqualTo(actual.getPaymentStatus()))
            .satisfies(e -> assertThat(e.getTransactionId()).as("check transactionId").isEqualTo(actual.getTransactionId()))
            .satisfies(e -> assertThat(e.getOrderStatus()).as("check orderStatus").isEqualTo(actual.getOrderStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdersUpdatableRelationshipsEquals(Orders expected, Orders actual) {
        assertThat(expected)
            .as("Verify Orders relationships")
            .satisfies(e -> assertThat(e.getUser()).as("check user").isEqualTo(actual.getUser()))
            .satisfies(e -> assertThat(e.getChief()).as("check chief").isEqualTo(actual.getChief()))
            .satisfies(e -> assertThat(e.getCity()).as("check city").isEqualTo(actual.getCity()));
    }
}
