package com.virality.dishly.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SignatureDishAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignatureDishAllPropertiesEquals(SignatureDish expected, SignatureDish actual) {
        assertSignatureDishAutoGeneratedPropertiesEquals(expected, actual);
        assertSignatureDishAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignatureDishAllUpdatablePropertiesEquals(SignatureDish expected, SignatureDish actual) {
        assertSignatureDishUpdatableFieldsEquals(expected, actual);
        assertSignatureDishUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignatureDishAutoGeneratedPropertiesEquals(SignatureDish expected, SignatureDish actual) {
        assertThat(expected)
            .as("Verify SignatureDish auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignatureDishUpdatableFieldsEquals(SignatureDish expected, SignatureDish actual) {
        assertThat(expected)
            .as("Verify SignatureDish relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignatureDishUpdatableRelationshipsEquals(SignatureDish expected, SignatureDish actual) {
        assertThat(expected)
            .as("Verify SignatureDish relationships")
            .satisfies(e -> assertThat(e.getChief()).as("check chief").isEqualTo(actual.getChief()));
    }
}
